language: php
sudo: false
dist: xenial
php:
  - 8.0
  - 7.4
  - 7.3
  - nightly

env:
  - TRAVIS_NODE_VERSION="14"
  - TRAVIS_NODE_VERSION="15"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - env: TRAVIS_NODE_VERSION="15"

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.yarn-cache
    - vendor

before_install:
  - composer self-update
  - source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
  - export PATH=$HOME/.yarn/bin:$PATH && travis_retry curl -o- -L https://yarnpkg.com/install.sh | bash

install:
  - node -v && yarn -V
  - travis_retry yarn
  - composer install -o --prefer-dist --no-interaction

script:
  - yarn run test
  - yarn run build
  - yarn run rmdist
  - yarn run build
  - composer test
